# Generated by Django 5.1 on 2024-08-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBRIRecord',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('adj_close_price', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
